### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Pilvinen** [julianlam/nodebb-plugin-gravatar#3]
Nodebb 0.9.1
Gravatar 1.0.4

1/12 22:17 [23853] - info: NodeBB Ready
1/12 22:17 [23853] - info: Enabling 'trust proxy'
1/12 22:17 [23853] - info: NodeBB is now listening on: 0.0.0.0:4567
1/12 22:17 [23853] - error: TypeError: Not a string or buffer
    at Hash.update (crypto.js:209:17)
    at sum (/home/minecraft/mynodebb/node_modules/nodebb-plugin-gravatar/library.js:124:9)
    at getGravatarUrl (/home/minecraft/mynodebb/node_modules/nodebb-plugin-gravatar/library.js:108:50)
    at /home/minecraft/mynodebb/node_modules/nodebb-plugin-gravatar/library.js:86:24
    at /home/minecraft/mynodebb/src/database/redis/hash.js:31:4
    at /home/minecraft/mynodebb/src/database/redis/hash.js:37:4
    at /home/minecraft/mynodebb/src/database/redis/hash.js:66:4
    at /home/minecraft/mynodebb/node_modules/redis/index.js:1138:13
    at try_callback (/home/minecraft/mynodebb/node_modules/redis/index.js:573:9)
    at RedisClient.return_reply (/home/minecraft/mynodebb/node_modules/redis/index.js:661:13)
3 restarts in 10 seconds, most likely an error on startup. Halting.

**Comment by julianlam** [comment]
@Pilvinen let me know if this is still an issue, thanks.
